### ISSUE TITLE
DEVELOP 05: Domain Modeling

### ISSUE THREAD

**Issue by jerry914** [SOA-SVM/TrailSmith#20]
## Task

- [x] Update the description of your project
- [x] Create the domain objects you might need
- [x] Develop your Web Application
- [ ] Deploy your Web application to Heroku (AWS)

I couldn't find your Heroku Web App URL in the [Google Team Sheet](https://docs.google.com/spreadsheets/d/1in8nvVFMh99L_NCA-PDzP0xR529cWyqTXr9tJljar0M/edit?gid=819082833#gid=819082833). Please make sure your application is deployed online. Feel free to ask for assistance on Teams if you need any help.

## RuboCop/Code Smell Offenses

N/A

You're doing great—just one more step to go!

**Comment by soumyaray** [comment]
Hey folks, apart from the `score` method of `Spot` entity, it seems your app is missing any value-adding logic. Would you like to have a session with me to figure out what your value-adding logic is, and when/where it might be hiding?
